project:
  type: default
  output-dir: _output

execute:
  # python: .venv/bin/python
  freeze: false

format:
  html:
    theme: cosmo
    highlight-style: github
    code-fold: false
    code-tools: true
    fig-align: center
    embed-resources: true
    toc: true
    toc-depth: 2
